### ISSUE TITLE
Full Dockerfile and docker-compose solution

### ISSUE THREAD

**Issue by fidoriel** [PatWie/excalidraw-complete#1]
This project looks great. Do you have or plan to offer independent docker images for use with docker compose. This would make it very easy to integrate this with for example nginx-proxy to self-host it without knowledge about the project.

**Comment by PatWie** [comment]
Could you please add more details. I think I am lacking some context here. Note, this binary is all-in-one. You are free to add an NGINX reverse proxy in front of it. But I don't see the advantage of a docker-compose file. (I am really curious to understand why this is needed.)

**Comment by fidoriel** [comment]
This would be just ease of use and convenience (not that a single executable is not easy but it does not integrate with a docker environment). I could directly integrate this with my existing docker compose environment by just using a prebuild docker image. It would be great if you could provide a prebuild docker image via a registry. Watchtower can automatically pull new images and replace the old ones. Docker makes things easier within my deployment processes. I do not deploy any web services without docker anymore. Docker Compose would just be a usage example for the docker image. Which ports, volumes/data dirs etc.

**Comment by PatWie** [comment]
Happy to accept a PR at some point, but I first should try to make it work (or alternatively just cry). Given this is just a fun project, I do not necessarily see the need to distribute it widely at the moment.

**Comment by fidoriel** [comment]
OK, fine, I will try to provide one, if the project is ready :)

**Comment by PatWie** [comment]
The latest commit in firebase-patch contains now a Dockerfile which I tested with AWS Fargate.
