### ISSUE TITLE
how to save to disk

### ISSUE THREAD

**Issue by Christian-Klempau** [PatWie/excalidraw-complete#5]
I am running the project with:

 `STORAGE_TYPE=filesystem LOCAL_STORAGE_PATH="/home/<my-user>/excalidraw/files" ./excalidraw-complete`

The server on `3002` works perfect!

But how exactly does the local storage work? It is not saving any drawings to that folder, and if I click `Ctrl+S`, it just downloads the file to `~./Downloads/`.

Any help appreciated!

**Comment by PatWie** [comment]
Can you please double check?

https://github.com/PatWie/excalidraw-complete/blob/3893dfb13e164d644222c8683d320f4c90127387/stores/storage.go#L18-L19

is setting the correct path. It is not about Ctrl+S. It is about the button "Export Link".

**Comment by Christian-Klempau** [comment]
Is it the button that makes a POST request to `http://localhost:3002/api/v2/post/`?
That request hangs and gives timeout :/
