### ISSUE TITLE
Error on startup of self-compiled binary in firebase-patch branch

### ISSUE THREAD

**Issue by codiflow** [PatWie/excalidraw-complete#6]
Thank you for this excellent solution – I was trying to port the fork at https://github.com/b310-digital/excalidraw together with a httpBackend solution to the recent version of Excalidraw but too much has changed in the last months so it feels like a rabbit hole. This is how I found your approach and it seems to be more lightweight (and future update-proof), so I will give it a Go (🤪).

As I'm building from source I went through the steps and as some of them are not necessary anymore I'll provide you an updated list of it as a PR (together with a big thanxx 🙏)

But at first I ran into a serious issue within the `firebase-patch` branch:

## Working
`git checkout main`
`go build -o excalidraw-complete main.go`
`STORAGE_TYPE=sqlite DATA_SOURCE_NAME=/root/test.sqlite ./excalidraw-complete`

Response:
```
listen on 3002
```

Browser output: Everythings working (apart from Google being still involved).

## Not working
`git checkout firebase-patch`
`go build -o excalidraw-complete main.go`
`STORAGE_TYPE=sqlite DATA_SOURCE_NAME=/root/test.sqlite ./excalidraw-complete`

Response:
```
&{0xc000037800 0xc0001a0cf0 <nil> 0x27e3f20 0x27e3f20 0xc00004bb60 0xc00004bb80 0xc00004bba0 0x27e3f20 true 0xc0000a5a00 <nil> /socket.io 0xc0001eadc0 45000000000 <nil> 0x93e2a0}
listen on 3002
```

Browser output: **File not found**

Do you have a clue whats wrong with the firebase-patch version?

**Comment by codiflow** [comment]
I already found out that this line is throwing the error – but I'm totally lost interpreting it 😅

https://github.com/PatWie/excalidraw-complete/blob/eea09906f46a73efbe720e5095b53104aa66c4e1/main.go#L213

**Comment by PatWie** [comment]
Maybe the firebase branch did change too much. I should have another look. But great news, that there is really no phone-home anymore. Will label this as a bug to being forced merging a working version into main.

**Comment by PatWie** [comment]
I did push my local commits. You probably saw the issue with "/" not being handled as "index.html". Feel free to re-open.
